CREATE DATABASE IF NOT EXISTS bugtrackerapp;

USE bugtrackerapp;

CREATE TABLE IF NOT EXISTS Project (
  projectId INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  updated_by VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Team (
  teamId INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  updated_by VARCHAR(255) DEFAULT NULL
);
